// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: FC_Service_Message.proto
// Protobuf C++ Version: 5.29.3

#ifndef FC_5fService_5fMessage_2eproto_2epb_2eh
#define FC_5fService_5fMessage_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_FC_5fService_5fMessage_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_FC_5fService_5fMessage_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_FC_5fService_5fMessage_2eproto;
namespace fc {
class ServiceAnnounce;
struct ServiceAnnounceDefaultTypeInternal;
extern ServiceAnnounceDefaultTypeInternal _ServiceAnnounce_default_instance_;
}  // namespace fc
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace fc {
enum ServiceAnnounce_StatusEnum : int {
  ServiceAnnounce_StatusEnum_UNKNOWN = 0,
  ServiceAnnounce_StatusEnum_ONLINE = 1,
  ServiceAnnounce_StatusEnum_OFFLINE = 2,
  ServiceAnnounce_StatusEnum_ServiceAnnounce_StatusEnum_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  ServiceAnnounce_StatusEnum_ServiceAnnounce_StatusEnum_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool ServiceAnnounce_StatusEnum_IsValid(int value);
extern const uint32_t ServiceAnnounce_StatusEnum_internal_data_[];
constexpr ServiceAnnounce_StatusEnum ServiceAnnounce_StatusEnum_StatusEnum_MIN = static_cast<ServiceAnnounce_StatusEnum>(0);
constexpr ServiceAnnounce_StatusEnum ServiceAnnounce_StatusEnum_StatusEnum_MAX = static_cast<ServiceAnnounce_StatusEnum>(2);
constexpr int ServiceAnnounce_StatusEnum_StatusEnum_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor*
ServiceAnnounce_StatusEnum_descriptor();
template <typename T>
const std::string& ServiceAnnounce_StatusEnum_Name(T value) {
  static_assert(std::is_same<T, ServiceAnnounce_StatusEnum>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to StatusEnum_Name().");
  return ServiceAnnounce_StatusEnum_Name(static_cast<ServiceAnnounce_StatusEnum>(value));
}
template <>
inline const std::string& ServiceAnnounce_StatusEnum_Name(ServiceAnnounce_StatusEnum value) {
  return ::google::protobuf::internal::NameOfDenseEnum<ServiceAnnounce_StatusEnum_descriptor,
                                                 0, 2>(
      static_cast<int>(value));
}
inline bool ServiceAnnounce_StatusEnum_Parse(absl::string_view name, ServiceAnnounce_StatusEnum* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ServiceAnnounce_StatusEnum>(
      ServiceAnnounce_StatusEnum_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class ServiceAnnounce final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:fc.ServiceAnnounce) */ {
 public:
  inline ServiceAnnounce() : ServiceAnnounce(nullptr) {}
  ~ServiceAnnounce() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ServiceAnnounce* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ServiceAnnounce));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ServiceAnnounce(
      ::google::protobuf::internal::ConstantInitialized);

  inline ServiceAnnounce(const ServiceAnnounce& from) : ServiceAnnounce(nullptr, from) {}
  inline ServiceAnnounce(ServiceAnnounce&& from) noexcept
      : ServiceAnnounce(nullptr, std::move(from)) {}
  inline ServiceAnnounce& operator=(const ServiceAnnounce& from) {
    CopyFrom(from);
    return *this;
  }
  inline ServiceAnnounce& operator=(ServiceAnnounce&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ServiceAnnounce& default_instance() {
    return *internal_default_instance();
  }
  static inline const ServiceAnnounce* internal_default_instance() {
    return reinterpret_cast<const ServiceAnnounce*>(
        &_ServiceAnnounce_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(ServiceAnnounce& a, ServiceAnnounce& b) { a.Swap(&b); }
  inline void Swap(ServiceAnnounce* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ServiceAnnounce* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ServiceAnnounce* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ServiceAnnounce>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ServiceAnnounce& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ServiceAnnounce& from) { ServiceAnnounce::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ServiceAnnounce* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "fc.ServiceAnnounce"; }

 protected:
  explicit ServiceAnnounce(::google::protobuf::Arena* arena);
  ServiceAnnounce(::google::protobuf::Arena* arena, const ServiceAnnounce& from);
  ServiceAnnounce(::google::protobuf::Arena* arena, ServiceAnnounce&& from) noexcept
      : ServiceAnnounce(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using StatusEnum = ServiceAnnounce_StatusEnum;
  static constexpr StatusEnum UNKNOWN = ServiceAnnounce_StatusEnum_UNKNOWN;
  static constexpr StatusEnum ONLINE = ServiceAnnounce_StatusEnum_ONLINE;
  static constexpr StatusEnum OFFLINE = ServiceAnnounce_StatusEnum_OFFLINE;
  static inline bool StatusEnum_IsValid(int value) {
    return ServiceAnnounce_StatusEnum_IsValid(value);
  }
  static constexpr StatusEnum StatusEnum_MIN = ServiceAnnounce_StatusEnum_StatusEnum_MIN;
  static constexpr StatusEnum StatusEnum_MAX = ServiceAnnounce_StatusEnum_StatusEnum_MAX;
  static constexpr int StatusEnum_ARRAYSIZE = ServiceAnnounce_StatusEnum_StatusEnum_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* StatusEnum_descriptor() {
    return ServiceAnnounce_StatusEnum_descriptor();
  }
  template <typename T>
  static inline const std::string& StatusEnum_Name(T value) {
    return ServiceAnnounce_StatusEnum_Name(value);
  }
  static inline bool StatusEnum_Parse(absl::string_view name, StatusEnum* value) {
    return ServiceAnnounce_StatusEnum_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kStatusFieldNumber = 1,
  };
  // .fc.ServiceAnnounce.StatusEnum status = 1;
  void clear_status() ;
  ::fc::ServiceAnnounce_StatusEnum status() const;
  void set_status(::fc::ServiceAnnounce_StatusEnum value);

  private:
  ::fc::ServiceAnnounce_StatusEnum _internal_status() const;
  void _internal_set_status(::fc::ServiceAnnounce_StatusEnum value);

  public:
  // @@protoc_insertion_point(class_scope:fc.ServiceAnnounce)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ServiceAnnounce& from_msg);
    int status_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_FC_5fService_5fMessage_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ServiceAnnounce

// .fc.ServiceAnnounce.StatusEnum status = 1;
inline void ServiceAnnounce::clear_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = 0;
}
inline ::fc::ServiceAnnounce_StatusEnum ServiceAnnounce::status() const {
  // @@protoc_insertion_point(field_get:fc.ServiceAnnounce.status)
  return _internal_status();
}
inline void ServiceAnnounce::set_status(::fc::ServiceAnnounce_StatusEnum value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:fc.ServiceAnnounce.status)
}
inline ::fc::ServiceAnnounce_StatusEnum ServiceAnnounce::_internal_status() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::fc::ServiceAnnounce_StatusEnum>(_impl_.status_);
}
inline void ServiceAnnounce::_internal_set_status(::fc::ServiceAnnounce_StatusEnum value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace fc


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::fc::ServiceAnnounce_StatusEnum> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::fc::ServiceAnnounce_StatusEnum>() {
  return ::fc::ServiceAnnounce_StatusEnum_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // FC_5fService_5fMessage_2eproto_2epb_2eh
