// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: FC_Service_Message.proto
// Protobuf C++ Version: 5.29.3

#include "FC_Service_Message.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace fc {

inline constexpr ServiceAnnounce::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : status_{static_cast< ::fc::ServiceAnnounce_StatusEnum >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ServiceAnnounce::ServiceAnnounce(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ServiceAnnounceDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ServiceAnnounceDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ServiceAnnounceDefaultTypeInternal() {}
  union {
    ServiceAnnounce _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ServiceAnnounceDefaultTypeInternal _ServiceAnnounce_default_instance_;
}  // namespace fc
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_FC_5fService_5fMessage_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_FC_5fService_5fMessage_2eproto = nullptr;
const ::uint32_t
    TableStruct_FC_5fService_5fMessage_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::fc::ServiceAnnounce, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::fc::ServiceAnnounce, _impl_.status_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::fc::ServiceAnnounce)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::fc::_ServiceAnnounce_default_instance_._instance,
};
const char descriptor_table_protodef_FC_5fService_5fMessage_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\030FC_Service_Message.proto\022\002fc\"u\n\017Servic"
    "eAnnounce\022.\n\006status\030\001 \001(\0162\036.fc.ServiceAn"
    "nounce.StatusEnum\"2\n\nStatusEnum\022\013\n\007UNKNO"
    "WN\020\000\022\n\n\006ONLINE\020\001\022\013\n\007OFFLINE\020\002b\006proto3"
};
static ::absl::once_flag descriptor_table_FC_5fService_5fMessage_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_FC_5fService_5fMessage_2eproto = {
    false,
    false,
    157,
    descriptor_table_protodef_FC_5fService_5fMessage_2eproto,
    "FC_Service_Message.proto",
    &descriptor_table_FC_5fService_5fMessage_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_FC_5fService_5fMessage_2eproto::offsets,
    file_level_enum_descriptors_FC_5fService_5fMessage_2eproto,
    file_level_service_descriptors_FC_5fService_5fMessage_2eproto,
};
namespace fc {
const ::google::protobuf::EnumDescriptor* ServiceAnnounce_StatusEnum_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_FC_5fService_5fMessage_2eproto);
  return file_level_enum_descriptors_FC_5fService_5fMessage_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t ServiceAnnounce_StatusEnum_internal_data_[] = {
    196608u, 0u, };
bool ServiceAnnounce_StatusEnum_IsValid(int value) {
  return 0 <= value && value <= 2;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr ServiceAnnounce_StatusEnum ServiceAnnounce::UNKNOWN;
constexpr ServiceAnnounce_StatusEnum ServiceAnnounce::ONLINE;
constexpr ServiceAnnounce_StatusEnum ServiceAnnounce::OFFLINE;
constexpr ServiceAnnounce_StatusEnum ServiceAnnounce::StatusEnum_MIN;
constexpr ServiceAnnounce_StatusEnum ServiceAnnounce::StatusEnum_MAX;
constexpr int ServiceAnnounce::StatusEnum_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
// ===================================================================

class ServiceAnnounce::_Internal {
 public:
};

ServiceAnnounce::ServiceAnnounce(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:fc.ServiceAnnounce)
}
ServiceAnnounce::ServiceAnnounce(
    ::google::protobuf::Arena* arena, const ServiceAnnounce& from)
    : ServiceAnnounce(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE ServiceAnnounce::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ServiceAnnounce::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.status_ = {};
}
ServiceAnnounce::~ServiceAnnounce() {
  // @@protoc_insertion_point(destructor:fc.ServiceAnnounce)
  SharedDtor(*this);
}
inline void ServiceAnnounce::SharedDtor(MessageLite& self) {
  ServiceAnnounce& this_ = static_cast<ServiceAnnounce&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* ServiceAnnounce::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ServiceAnnounce(arena);
}
constexpr auto ServiceAnnounce::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(ServiceAnnounce),
                                            alignof(ServiceAnnounce));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ServiceAnnounce::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ServiceAnnounce_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ServiceAnnounce::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ServiceAnnounce>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ServiceAnnounce::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ServiceAnnounce>(), &ServiceAnnounce::ByteSizeLong,
            &ServiceAnnounce::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ServiceAnnounce, _impl_._cached_size_),
        false,
    },
    &ServiceAnnounce::kDescriptorMethods,
    &descriptor_table_FC_5fService_5fMessage_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ServiceAnnounce::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> ServiceAnnounce::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::fc::ServiceAnnounce>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .fc.ServiceAnnounce.StatusEnum status = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ServiceAnnounce, _impl_.status_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ServiceAnnounce, _impl_.status_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .fc.ServiceAnnounce.StatusEnum status = 1;
    {PROTOBUF_FIELD_OFFSET(ServiceAnnounce, _impl_.status_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void ServiceAnnounce::Clear() {
// @@protoc_insertion_point(message_clear_start:fc.ServiceAnnounce)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.status_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ServiceAnnounce::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ServiceAnnounce& this_ = static_cast<const ServiceAnnounce&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ServiceAnnounce::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ServiceAnnounce& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:fc.ServiceAnnounce)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // .fc.ServiceAnnounce.StatusEnum status = 1;
          if (this_._internal_status() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                1, this_._internal_status(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:fc.ServiceAnnounce)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ServiceAnnounce::ByteSizeLong(const MessageLite& base) {
          const ServiceAnnounce& this_ = static_cast<const ServiceAnnounce&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ServiceAnnounce::ByteSizeLong() const {
          const ServiceAnnounce& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:fc.ServiceAnnounce)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // .fc.ServiceAnnounce.StatusEnum status = 1;
            if (this_._internal_status() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_status());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ServiceAnnounce::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ServiceAnnounce*>(&to_msg);
  auto& from = static_cast<const ServiceAnnounce&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:fc.ServiceAnnounce)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_status() != 0) {
    _this->_impl_.status_ = from._impl_.status_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ServiceAnnounce::CopyFrom(const ServiceAnnounce& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:fc.ServiceAnnounce)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ServiceAnnounce::InternalSwap(ServiceAnnounce* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.status_, other->_impl_.status_);
}

::google::protobuf::Metadata ServiceAnnounce::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace fc
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_FC_5fService_5fMessage_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
